### ISSUE TITLE
Missing focus highlight in split view

### ISSUE THREAD

**Issue by nanocryk** [mohvn/dropshadow-zenbrowser#3]
Firstly, your theme clearly improves the look and feel of the UI! Love it!

A slight downside is that when spliting tabs, the focused view is no longer highlighted.

Here is my suggestion to highlight again the focused tab:
```css
#tabbrowser-tabpanels[zen-split-view='true'] .browserSidebarContainer.deck-selected {
    outline: 2px solid color-mix(in srgb, var(--zen-primary-color) 50%, transparent) !important;
} 
```
